services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: proyectoef
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - proyectoef_data:/var/lib/postgresql/data  # Cambié el nombre del volumen a "trabajoef_data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proyectoef"]  # Cambié el nombre de la base de datos a "trabajoef"
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ..                   
      dockerfile: Api/Dockerfile  
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=proyectoef;Username=postgres;Password=postgres"  # Cambié la base de datos a "trabajoef"
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  proyectoef_data: